travis:
  secure:
    BINSTAR_TOKEN: gCGcM7L7GcjaR9kDLrPXiG7kRiSMc7g4CTh27SAM7OOtmHmwbbG+VYIIQgjhrUCkoJUliFnP4ulazkVGvkXpvJzLpzrLJ9x+ZMTM3s+rmZO3zhAXcIi8+kIABV16buEPHqPCotiEJ7rH8Ladx9dpXjUi7CPEiO2mkfpOm28aOWfgNVpc2BXUrY8fs6zqqX2d3IhrUISLVCM8mnjDITghunJrvC6CbfUzglnfLqxXdNfgYRCCNBMoL/uX3sIJ258T5A1owA/DJ5aJRu75HaWArVSNmOeCwVxSnCPNK4G43u4iPCoGT0HkM8tBbkk2p1jqn8nvGikl9PErqihcWepTdPaDx1swxRAsm6gm7Ff0RGIXb+mw3nZzIV8ysEKQmfG1nZs60s5Z/dgjWw+eMN8X2ZZd3jXD1UvnRkv5wERqiWOekC7Tq+dvm6LsqhomQ5K/n1oRp8O5QGsTD64rpZm1rZQbyZ9lEDBMqU4hFSMr17L1QBv3k3GEBVnu5JiKufR0V6OiknRBZ3wZ5JX3XcW61KuUr2irzbseR7MNPccdykH83ooAOR5FQo9zS6JS7uT6jpwdhXMPuxNx/rDAXYWmcERw0Q78wmP7PeY9kDS+Zts7NB/uamZ/NjlrKKovVdb3g92cj107a/mnNwbWd1A1UAVJYkKAYfTnNl5aQjHRznE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
